/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssjj_androidmvpdemo_ndk_MyJni */

#ifndef _Included_com_ssjj_androidmvpdemo_ndk_MyJni
#define _Included_com_ssjj_androidmvpdemo_ndk_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ssjj_androidmvpdemo_ndk_MyJni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssjj_androidmvpdemo_ndk_MyJni_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
